# Trabajo Práctico: Impacto de la IA en el Empleo (2020-2026)
## Sector Asignado: Finanzas (Finance)

### 1. Introducción Académica
El avance de la Inteligencia Artificial no es solo un fenómeno técnico, sino una fuerza socioeconómica que está redefiniendo la naturaleza del trabajo. En los próximos años, diversos sectores experimentarán cambios sin precedentes en sus estructuras salariales, demandas de habilidades y estabilidad laboral. Este Trabajo Práctico propone analizar estas tendencias con rigor científico y pensamiento crítico.

### 2. Ficha del Proyecto: Grupo 2
*   **Sector**: Finanzas.
*   **Objetivo General**: Analizar el impacto de la IA en la volatilidad salarial y la brecha de habilidades dentro del sector financiero, identificando países con mayor estrés de transición.

#### Setup y parametros

In [43]:
import pandas as pd
# Display para mostrar los DF de manera más prolija
from IPython.display import display

csvBaseFilePath = 'ai_job_replacement_dirty.csv'

### 3. Fase I: Diagnóstico y Saneamiento (Caja Negra)
Ustedes trabajarán con la fuente de datos `ai_job_replacement_dirty.csv`. **Advertencia**: La fuente posee anomalías estructuradas.
- **Auditoría de Calidad**: Realicen un reporte inicial sobre el estado de la información. Deben identificar inconsistencias lógicas, errores de formato y vacíos de datos sin guía externa.
- **Protocolo de Curación**: Implementen y documenten un proceso sistemático de limpieza. Cada decisión (casteo de tipos, manejo de nulos, eliminación de duplicados) debe estar técnicamente justificada en su bitácora.
- **Normalización**: Traduzcan y estandaricen los campos para asegurar una lectura fluida en español.

#### Carga y muestra rápida

In [44]:
df = pd.read_csv(csvBaseFilePath)

print("Info del DataFrame:")
display(df.info())

print("Primeras filas del DataFrame:")
display(df.head())
print("Últimas filas del DataFrame:")
display(df.tail())
print("Muestra aleatoria de 10 filas:")
display(df.sample(n=10))

Info del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15050 entries, 0 to 15049
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   job_id                       15050 non-null  int64
 1   job_role                     15050 non-null  object
 2   industry                     14299 non-null  object
 3   country                      15050 non-null  object
 4   year                         15050 non-null  float64
 5   automation_risk_percent      14298 non-null  float64
 6   ai_replacement_score         15050 non-null  float64
 7   skill_gap_index              15050 non-null  float64
 8   salary_before_usd            14297 non-null  object
 9   salary_after_usd             14296 non-null  object
 10  salary_change_percent        15050 non-null  float64
 11  skill_demand_growth_percent  15050 non-null  float64
 12  remote_feasibility_score     15050 non-null  float64
 13  ai_adoption_level            15050 non-null  float64
 14  education_requirement_level  15050 non-null  int64
 15  automation_risk_category     15050 non-null  object
 16  skill_transition_pressure    15050 non-null  float64
 17  wage_volatility_index        15050 non-null  float64
 18  reskilling_urgency_score     15050 non-null  float64
 19  ai_disruption_intensity      15050 non-null  float64
dtypes: float64(12), int64(2), object(6)
memory usage: 2.3+ MB

None

Primeras filas del DataFrame:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
0,0,Data Analyst,Technology,Canada,2021.0,26.22,30.94,73.20,101839.02,99454.42,-2.34,2.66,15.23,86.62,2,Low,49.710,2.34,33.150,22.711764
1,1,Accountant,FINANCE,Brazil,2020.0,52.08,56.41,2.06,146389.18,139516.59,-4.69,10.43,26.36,18.34,5,Medium,27.070,4.69,22.857,9.551472
2,2,Teacher,Technology,USA,2020.0,31.30,31.61,43.19,64947.5,58369.41,-10.13,8.14,36.29,36.64,2,Medium,37.245,10.13,28.516,11.468320
3,3,Customer Support Rep,Technology,Brazil,2021.0,56.92,63.42,19.97,NaN,86715.7,-5.44,6.11,64.68,17.05,5,Medium,38.445,5.44,30.391,9.704860
4,4,Teacher,manufacturing,Japan,2024.0,14.55,17.17,96.56,127007.68,NaN,-6.01,2.08,71.58,44.02,3,Low,55.555,6.01,36.591,6.404910

Últimas filas del DataFrame:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
15045,13610,Marketing Specialist,Transportation,Australia,2022.0,22.03,20.22,39.80,78791.26,NaN,-0.24,19.22,15.01,60.05,3,Low,30.915,0.24,20.824,13.229015
15046,1670,Financial Analyst,Manufacturing,Australia,2024.0,72.52,76.49,68.93,110112.87,130705.5,18.70,0.01,16.27,85.99,4,High,70.725,18.70,55.297,62.359948
15047,371,Customer Support Rep,NaN,Japan,2021.0,46.07,46.12,5.62,88931.49,84546.07,-4.93,19.44,68.97,26.02,1,Medium,25.845,4.93,21.593,11.987414
15048,14663,Customer Support Rep,Technology,India,2021.0,43.76,48.94,10.29,81611.13,90995.5,11.50,-16.04,15.46,3.36,4,Medium,27.025,11.50,24.041,1.470336
15049,12202,Truck Driver,Manufacturing,USA,2025.0,89.90,107.87,59.36,142175.13,132660.17,-6.69,10.74,71.55,79.01,5,High,74.630,6.69,55.775,71.029990

Muestra aleatoria de 10 filas:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
13471,13471,HR Manager,healthcare,India,2025.0,59.06,63.53,89.95,90740.02,96559.4,6.41,-1.02,23.28,67.36,3,Medium,74.505,6.41,52.532,39.782816
7727,7727,Customer Support Rep,Manufacturing,Singapore,2021.0,89.42,106.43,21.04,97327.6,NaN,10.92,6.10,72.19,60.74,2,High,55.230,10.92,45.356,54.313708
609,609,HR Manager,Transportation,Singapore,2023.0,33.25,35.92,76.53,141528.42,149956.31,5.95,-0.90,76.47,6.38,1,Medium,54.890,5.95,38.044,2.121350
10858,10858,Software Engineer,NaN,Germany,2022.0,47.19,54.16,66.59,"$86,991.33",83253.26,-4.30,23.64,68.88,78.04,1,Medium,56.890,4.30,40.143,36.827076
3133,3133,Mechanical Engineer,Energy,Canada,2026.0,63.27,60.11,56.79,83958.99,78210.9,-6.85,2.38,25.08,36.70,4,High,60.030,6.85,44.400,23.220090
13317,13317,Truck Driver,Retail,USA,2022.0,64.65,56.42,39.19,50314.9,50314.9,5.00,1.06,54.22,80.41,3,High,51.920,7.50,39.867,51.985065
14521,14521,Teacher,Finance,Australia,2021.0,27.15,29.31,18.79,89367.03,89769.71,0.45,-5.12,83.92,48.37,5,Low,22.970,0.45,16.632,13.132455
8666,8666,Teacher,Technology,Germany,2025.0,56.14,56.59,61.34,33736.87,34527.37,2.34,-0.13,86.31,35.94,3,Medium,58.740,2.34,41.560,20.176716
5943,5943,Accountant,finance,India,2025.0,64.08,58.85,53.20,67624.92,69294.51,2.47,-11.82,98.90,21.46,3,High,58.640,2.47,42.333,13.751568
13278,13278,Mechanical Engineer,Manufacturing,UK,2024.0,64.05,73.23,68.98,50043.62,47851.27,-4.38,3.38,77.75,69.11,4,High,66.515,4.38,47.628,44.264955

#### Analisis de vacios y filas duplicadas

In [ ]:
print("Conteo de valores nulos por columna:")
display(df.isnull().sum())

print("Número de filas repetidas:", df.duplicated().sum())

Conteo de valores nulos por columna:

job_id                           0
job_role                         0
industry                       751
country                          0
year                             0
automation_risk_percent        752
ai_replacement_score             0
skill_gap_index                  0
salary_before_usd              753
salary_after_usd               754
salary_change_percent            0
skill_demand_growth_percent      0
remote_feasibility_score         0
ai_adoption_level                0
education_requirement_level      0
automation_risk_category         0
skill_transition_pressure        0
wage_volatility_index            0
reskilling_urgency_score         0
ai_disruption_intensity          0
dtype: int64

Número de filas repetidas: 50

#### Identificación de inconsistencias en valores categoricos

In [46]:
object_columns = df.select_dtypes(include=['object']).columns

for col in object_columns:
    print(f"Distribución de categorias para {col}:")
    display(df[col].value_counts(normalize=True, sort=False).sort_index())

Distribución de categorias para job_role:

job_role
Accountant              0.094352
Customer Support Rep    0.100997
Data Analyst            0.101860
Financial Analyst       0.096412
HR Manager              0.100066
Marketing Specialist    0.103522
Mechanical Engineer     0.101661
Software Engineer       0.098007
Teacher                 0.103256
Truck Driver            0.099867
Name: proportion, dtype: float64

Distribución de categorias para industry:

industry
 Education          0.005944
 Energy             0.006434
 Finance            0.006294
 Healthcare         0.006224
 Manufacturing      0.005315
 Retail             0.005735
 Technology         0.006714
 Transportation     0.007833
EDUCATION           0.006294
ENERGY              0.005525
Education           0.102874
Energy              0.106441
FINANCE             0.006924
Finance             0.110287
HEALTHCARE          0.005665
Healthcare          0.106441
MANUFACTURING       0.005944
Manufacturing       0.102525
RETAIL              0.005245
Retail              0.106861
TECHNOLOGY          0.005525
TRANSPORTATION      0.005245
Technology          0.107490
Transportation      0.107840
education           0.006364
energy              0.006434
finance             0.005944
healthcare          0.007133
manufacturing       0.007413
retail              0.006364
technology          0.006434
transportation      0.006294
Name: proportion, dtype: float64

Distribución de categorias para country:

country
Australia    0.109635
Brazil       0.110565
Canada       0.109236
Germany      0.105781
India        0.109568
Japan        0.109435
Singapore    0.116412
UK           0.114086
USA          0.115282
Name: proportion, dtype: float64

Distribución de categorias para salary_before_usd:

salary_before_usd
$100,225.36    0.00007
$100,226.42    0.00007
$100,242.03    0.00007
$100,247.07    0.00007
$100,347.96    0.00007
                ...
99963.01       0.00007
99964.99       0.00007
99966.34       0.00007
99976.17       0.00007
99990.29       0.00007
Name: proportion, Length: 14235, dtype: float64

Distribución de categorias para salary_after_usd:

salary_after_usd
$94,964.93    0.00007
100008.15     0.00007
100046.45     0.00007
100057.69     0.00007
100058.68     0.00007
               ...
99979.45      0.00007
99982.95      0.00007
99987.37      0.00007
99990.31      0.00007
99993.82      0.00007
Name: proportion, Length: 14239, dtype: float64

Distribución de categorias para automation_risk_category:

automation_risk_category
High      0.299601
Low       0.269302
Medium    0.431096
Name: proportion, dtype: float64

### 4. Fase II: Análisis Estadístico y Exploratorio (EDA)
Utilizando las librerías Pandas y NumPy, resuelvan las siguientes problemáticas:
- **Volatilidad de Ingresos**: Calculen el rango y la varianza de los salarios antes y después de la IA. ¿Qué nos dice esto sobre la estabilidad del sector?
- **Brecha de Habilidades**: Determinen el promedio de `skill_gap_index` por país y encuentren dónde es más crítico el desfase formativo.
- **Detección de Outliers**: Identifiquen salarios que desafíen los rangos normales del mercado (valores negativos o extremos) y decidan su tratamiento.

### 5. Fase III: Visualización y Comunicación
Diseñen las siguientes piezas utilizando Matplotlib:
- **Gráfico de Evolución**: Tendencia anual del salario promedio en finanzas desde 2020 a 2026.
- **Gráfico de Distribución (Pie/Pie Chart)**: Distribución de los roles según su categoría de riesgo de automatización.
- **Heatmap o Barras Geográficas**: Comparativa del `ai_adoption_level` por país para este sector.

### 6. Fase IV: Reflexión Crítica (Anti-LLM)
*Responda basándose estrictamente en los hallazgos de su procesamiento de datos:*
- ¿Existe evidencia de que la IA esté "empobreciendo" los roles tradicionales de finanzas?
- Según sus datos, ¿la factibilidad de trabajo remoto protege o expone más al trabajador financiero frente al reemplazo por IA?

### 7. Requerimientos de Entrega y Defensa
1.  **Informe Profesional**: PDF o Markdown con resumen ejecutivo, bitácora de saneamiento e interpretación de resultados.
2.  **Código Fuente**: Script o Notebook estructurado, comentado y reproducible.
3.  **Defensa Oral**: Justificación técnica de la limpieza e interpretación de las visualizaciones ante el curso.