# Trabajo Práctico: Impacto de la IA en el Empleo (2020-2026)
## Sector Asignado: Finanzas (Finance)

### 1. Introducción Académica
El avance de la Inteligencia Artificial no es solo un fenómeno técnico, sino una fuerza socioeconómica que está redefiniendo la naturaleza del trabajo. En los próximos años, diversos sectores experimentarán cambios sin precedentes en sus estructuras salariales, demandas de habilidades y estabilidad laboral. Este Trabajo Práctico propone analizar estas tendencias con rigor científico y pensamiento crítico.

### 2. Ficha del Proyecto: Grupo 2
*   **Sector**: Finanzas.
*   **Objetivo General**: Analizar el impacto de la IA en la volatilidad salarial y la brecha de habilidades dentro del sector financiero, identificando países con mayor estrés de transición.

#### Setup y parametros

In [33]:
import pandas as pd
# Display para mostrar los DF de manera más prolija
from IPython.display import display

csvBaseFilePath = 'ai_job_replacement_dirty.csv'

### 3. Fase I: Diagnóstico y Saneamiento (Caja Negra)
Ustedes trabajarán con la fuente de datos `ai_job_replacement_dirty.csv`. **Advertencia**: La fuente posee anomalías estructuradas.
- **Auditoría de Calidad**: Realicen un reporte inicial sobre el estado de la información. Deben identificar inconsistencias lógicas, errores de formato y vacíos de datos sin guía externa.
- **Protocolo de Curación**: Implementen y documenten un proceso sistemático de limpieza. Cada decisión (casteo de tipos, manejo de nulos, eliminación de duplicados) debe estar técnicamente justificada en su bitácora.
- **Normalización**: Traduzcan y estandaricen los campos para asegurar una lectura fluida en español.

#### Carga y muestra rápida

In [34]:
df = pd.read_csv(csvBaseFilePath)

print("Tamaño DF:")
display(df.shape)
print("Columnas presentes en DF:")
display(df.dtypes)

# Visualización inicial de los datos
print("Primeras filas del DataFrame:")
display(df.head())
print("Últimas filas del DataFrame:")
display(df.tail())
print("Muestra aleatoria de 10 filas:")
display(df.sample(n=10))

Tamaño DF:

(15050, 20)

Columnas presentes en DF:

job_id                           int64
job_role                        object
industry                        object
country                         object
year                           float64
automation_risk_percent        float64
ai_replacement_score           float64
skill_gap_index                float64
salary_before_usd               object
salary_after_usd                object
salary_change_percent          float64
skill_demand_growth_percent    float64
remote_feasibility_score       float64
ai_adoption_level              float64
education_requirement_level      int64
automation_risk_category        object
skill_transition_pressure      float64
wage_volatility_index          float64
reskilling_urgency_score       float64
ai_disruption_intensity        float64
dtype: object

Primeras filas del DataFrame:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
0,0,Data Analyst,Technology,Canada,2021.0,26.22,30.94,73.20,101839.02,99454.42,-2.34,2.66,15.23,86.62,2,Low,49.710,2.34,33.150,22.711764
1,1,Accountant,FINANCE,Brazil,2020.0,52.08,56.41,2.06,146389.18,139516.59,-4.69,10.43,26.36,18.34,5,Medium,27.070,4.69,22.857,9.551472
2,2,Teacher,Technology,USA,2020.0,31.30,31.61,43.19,64947.5,58369.41,-10.13,8.14,36.29,36.64,2,Medium,37.245,10.13,28.516,11.468320
3,3,Customer Support Rep,Technology,Brazil,2021.0,56.92,63.42,19.97,NaN,86715.7,-5.44,6.11,64.68,17.05,5,Medium,38.445,5.44,30.391,9.704860
4,4,Teacher,manufacturing,Japan,2024.0,14.55,17.17,96.56,127007.68,NaN,-6.01,2.08,71.58,44.02,3,Low,55.555,6.01,36.591,6.404910

Últimas filas del DataFrame:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
15045,13610,Marketing Specialist,Transportation,Australia,2022.0,22.03,20.22,39.80,78791.26,NaN,-0.24,19.22,15.01,60.05,3,Low,30.915,0.24,20.824,13.229015
15046,1670,Financial Analyst,Manufacturing,Australia,2024.0,72.52,76.49,68.93,110112.87,130705.5,18.70,0.01,16.27,85.99,4,High,70.725,18.70,55.297,62.359948
15047,371,Customer Support Rep,NaN,Japan,2021.0,46.07,46.12,5.62,88931.49,84546.07,-4.93,19.44,68.97,26.02,1,Medium,25.845,4.93,21.593,11.987414
15048,14663,Customer Support Rep,Technology,India,2021.0,43.76,48.94,10.29,81611.13,90995.5,11.50,-16.04,15.46,3.36,4,Medium,27.025,11.50,24.041,1.470336
15049,12202,Truck Driver,Manufacturing,USA,2025.0,89.90,107.87,59.36,142175.13,132660.17,-6.69,10.74,71.55,79.01,5,High,74.630,6.69,55.775,71.029990

Muestra aleatoria de 10 filas:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
5572,5572,Mechanical Engineer,Retail,Brazil,2022.0,30.88,32.40,56.86,94590.81,91229.69,-3.55,3.73,86.52,88.65,2,Medium,43.870,3.55,30.475,27.375120
1062,1062,HR Manager,Technology,Singapore,2026.0,35.90,39.36,78.42,121594.22,110934.09,-8.77,11.60,40.42,46.98,3,Medium,57.160,8.77,40.517,16.865820
1873,1873,Teacher,NaN,India,2021.0,13.13,12.26,39.14,148790.58,152060.37,2.20,-9.34,98.86,79.20,5,Low,26.135,2.20,17.654,10.398960
9875,9875,Customer Support Rep,Finance,India,2022.0,87.91,75.31,60.12,104101.36,105177.58,1.03,0.64,72.48,91.01,1,High,74.015,1.03,53.509,80.006891
461,461,Data Analyst,Energy,Brazil,2025.0,29.20,25.23,17.09,"$80,177.37",83296.1,3.89,7.51,17.57,39.31,3,Low,23.145,3.89,17.974,11.478520
6829,6829,Mechanical Engineer,Transportation,Japan,2022.0,60.84,56.83,79.59,110761.6,117685.2,6.25,6.89,90.41,71.17,4,High,70.215,6.25,50.088,43.299828
12724,12724,Truck Driver,Education,UK,2026.0,50.36,42.39,54.59,140483.63,145441.78,3.53,18.84,16.77,65.58,3,Medium,52.475,3.53,37.580,33.026088
8503,8503,HR Manager,Retail,Singapore,2022.0,54.11,45.40,29.00,89785.74,110592.67,23.17,12.60,81.75,16.32,3,Medium,41.555,23.17,37.295,8.830752
784,784,Customer Support Rep,Energy,Canada,2025.0,NaN,39.13,63.38,60384.14,68178.27,12.91,30.88,68.99,23.32,5,Medium,48.800,12.91,36.575,7.980104
5017,5017,Financial Analyst,Healthcare,Japan,2023.0,60.62,65.40,51.44,63457.62,63781.39,0.51,19.39,15.33,91.86,1,High,56.030,0.51,39.833,55.685532

#### Analisis de vacios y filas duplicadas

In [35]:
print("Información general del DataFrame:")
display(df.info())
print("Conteo de valores nulos por columna:")
display(df.isnull().sum())

print("Número de filas repetidas:", df.duplicated().sum())

Información general del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15050 entries, 0 to 15049
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   job_id                       15050 non-null  int64
 1   job_role                     15050 non-null  object
 2   industry                     14299 non-null  object
 3   country                      15050 non-null  object
 4   year                         15050 non-null  float64
 5   automation_risk_percent      14298 non-null  float64
 6   ai_replacement_score         15050 non-null  float64
 7   skill_gap_index              15050 non-null  float64
 8   salary_before_usd            14297 non-null  object
 9   salary_after_usd             14296 non-null  object
 10  salary_change_percent        15050 non-null  float64
 11  skill_demand_growth_percent  15050 non-null  float64
 12  remote_feasibility_score     15050 non-null  float64
 13  ai_adoption_level            15050 non-null  float64
 14  education_requirement_level  15050 non-null  int64
 15  automation_risk_category     15050 non-null  object
 16  skill_transition_pressure    15050 non-null  float64
 17  wage_volatility_index        15050 non-null  float64
 18  reskilling_urgency_score     15050 non-null  float64
 19  ai_disruption_intensity      15050 non-null  float64
dtypes: float64(12), int64(2), object(6)
memory usage: 2.3+ MB

None

Conteo de valores nulos por columna:

job_id                           0
job_role                         0
industry                       751
country                          0
year                             0
automation_risk_percent        752
ai_replacement_score             0
skill_gap_index                  0
salary_before_usd              753
salary_after_usd               754
salary_change_percent            0
skill_demand_growth_percent      0
remote_feasibility_score         0
ai_adoption_level                0
education_requirement_level      0
automation_risk_category         0
skill_transition_pressure        0
wage_volatility_index            0
reskilling_urgency_score         0
ai_disruption_intensity          0
dtype: int64

Número de filas repetidas: 50

In [36]:
# Análisis de variables categóricas o de texto
print("Valores únicos en la columna job_role:")
display(df['job_role'].unique())
print("Número de valores únicos en la columna job_role:")
display(df['job_role'].nunique())
print("Proporciones porcentuales de los valores en la columna job_role:")
display(df['job_role'].value_counts(normalize=True))

Valores únicos en la columna job_role:

array(['Data Analyst', 'Accountant', 'Teacher', 'Customer Support Rep',
       'Software Engineer', 'Marketing Specialist', 'Financial Analyst',
       'HR Manager', 'Mechanical Engineer', 'Truck Driver'], dtype=object)

Número de valores únicos en la columna job_role:

10

Proporciones porcentuales de los valores en la columna job_role:

job_role
Marketing Specialist    0.103522
Teacher                 0.103256
Data Analyst            0.101860
Mechanical Engineer     0.101661
Customer Support Rep    0.100997
HR Manager              0.100066
Truck Driver            0.099867
Software Engineer       0.098007
Financial Analyst       0.096412
Accountant              0.094352
Name: proportion, dtype: float64

### 4. Fase II: Análisis Estadístico y Exploratorio (EDA)
Utilizando las librerías Pandas y NumPy, resuelvan las siguientes problemáticas:
- **Volatilidad de Ingresos**: Calculen el rango y la varianza de los salarios antes y después de la IA. ¿Qué nos dice esto sobre la estabilidad del sector?
- **Brecha de Habilidades**: Determinen el promedio de `skill_gap_index` por país y encuentren dónde es más crítico el desfase formativo.
- **Detección de Outliers**: Identifiquen salarios que desafíen los rangos normales del mercado (valores negativos o extremos) y decidan su tratamiento.

### 5. Fase III: Visualización y Comunicación
Diseñen las siguientes piezas utilizando Matplotlib:
- **Gráfico de Evolución**: Tendencia anual del salario promedio en finanzas desde 2020 a 2026.
- **Gráfico de Distribución (Pie/Pie Chart)**: Distribución de los roles según su categoría de riesgo de automatización.
- **Heatmap o Barras Geográficas**: Comparativa del `ai_adoption_level` por país para este sector.

### 6. Fase IV: Reflexión Crítica (Anti-LLM)
*Responda basándose estrictamente en los hallazgos de su procesamiento de datos:*
- ¿Existe evidencia de que la IA esté "empobreciendo" los roles tradicionales de finanzas?
- Según sus datos, ¿la factibilidad de trabajo remoto protege o expone más al trabajador financiero frente al reemplazo por IA?

### 7. Requerimientos de Entrega y Defensa
1.  **Informe Profesional**: PDF o Markdown con resumen ejecutivo, bitácora de saneamiento e interpretación de resultados.
2.  **Código Fuente**: Script o Notebook estructurado, comentado y reproducible.
3.  **Defensa Oral**: Justificación técnica de la limpieza e interpretación de las visualizaciones ante el curso.