# Trabajo Práctico: Impacto de la IA en el Empleo (2020-2026)
## Sector Asignado: Finanzas (Finance)

### 1. Introducción Académica
El avance de la Inteligencia Artificial no es solo un fenómeno técnico, sino una fuerza socioeconómica que está redefiniendo la naturaleza del trabajo. En los próximos años, diversos sectores experimentarán cambios sin precedentes en sus estructuras salariales, demandas de habilidades y estabilidad laboral. Este Trabajo Práctico propone analizar estas tendencias con rigor científico y pensamiento crítico.

### 2. Ficha del Proyecto: Grupo 2
*   **Sector**: Finanzas.
*   **Objetivo General**: Analizar el impacto de la IA en la volatilidad salarial y la brecha de habilidades dentro del sector financiero, identificando países con mayor estrés de transición.

#### Setup y parametros

In [316]:
import pandas as pd
import numpy as np
# Display para mostrar los DF de manera más prolija
from IPython.display import display

csv_base_file_path = '../MaterialBase/ai_job_replacement_dirty.csv'

### 3. Fase I: Diagnóstico y Saneamiento (Caja Negra)
Ustedes trabajarán con la fuente de datos `ai_job_replacement_dirty.csv`. **Advertencia**: La fuente posee anomalías estructuradas.
- **Auditoría de Calidad**: Realicen un reporte inicial sobre el estado de la información. Deben identificar inconsistencias lógicas, errores de formato y vacíos de datos sin guía externa.
- **Protocolo de Curación**: Implementen y documenten un proceso sistemático de limpieza. Cada decisión (casteo de tipos, manejo de nulos, eliminación de duplicados) debe estar técnicamente justificada en su bitácora.
- **Normalización**: Traduzcan y estandaricen los campos para asegurar una lectura fluida en español.

#### Carga y muestra rápida

In [317]:
df = pd.read_csv(csv_base_file_path)

print("Info del DataFrame:")
display(df.info())

print("Primeras filas del DataFrame:")
display(df.head())
print("Últimas filas del DataFrame:")
display(df.tail())
print("Muestra aleatoria de 10 filas:")
display(df.sample(n=10))

Info del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15050 entries, 0 to 15049
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   job_id                       15050 non-null  int64
 1   job_role                     15050 non-null  object
 2   industry                     14299 non-null  object
 3   country                      15050 non-null  object
 4   year                         15050 non-null  float64
 5   automation_risk_percent      14298 non-null  float64
 6   ai_replacement_score         15050 non-null  float64
 7   skill_gap_index              15050 non-null  float64
 8   salary_before_usd            14297 non-null  object
 9   salary_after_usd             14296 non-null  object
 10  salary_change_percent        15050 non-null  float64
 11  skill_demand_growth_percent  15050 non-null  float64
 12  remote_feasibility_score     15050 non-null  float64
 13  ai_adoption_level            15050 non-null  float64
 14  education_requirement_level  15050 non-null  int64
 15  automation_risk_category     15050 non-null  object
 16  skill_transition_pressure    15050 non-null  float64
 17  wage_volatility_index        15050 non-null  float64
 18  reskilling_urgency_score     15050 non-null  float64
 19  ai_disruption_intensity      15050 non-null  float64
dtypes: float64(12), int64(2), object(6)
memory usage: 2.3+ MB

None

Primeras filas del DataFrame:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
0,0,Data Analyst,Technology,Canada,2021.0,26.22,30.94,73.20,101839.02,99454.42,-2.34,2.66,15.23,86.62,2,Low,49.710,2.34,33.150,22.711764
1,1,Accountant,FINANCE,Brazil,2020.0,52.08,56.41,2.06,146389.18,139516.59,-4.69,10.43,26.36,18.34,5,Medium,27.070,4.69,22.857,9.551472
2,2,Teacher,Technology,USA,2020.0,31.30,31.61,43.19,64947.5,58369.41,-10.13,8.14,36.29,36.64,2,Medium,37.245,10.13,28.516,11.468320
3,3,Customer Support Rep,Technology,Brazil,2021.0,56.92,63.42,19.97,NaN,86715.7,-5.44,6.11,64.68,17.05,5,Medium,38.445,5.44,30.391,9.704860
4,4,Teacher,manufacturing,Japan,2024.0,14.55,17.17,96.56,127007.68,NaN,-6.01,2.08,71.58,44.02,3,Low,55.555,6.01,36.591,6.404910

Últimas filas del DataFrame:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
15045,13610,Marketing Specialist,Transportation,Australia,2022.0,22.03,20.22,39.80,78791.26,NaN,-0.24,19.22,15.01,60.05,3,Low,30.915,0.24,20.824,13.229015
15046,1670,Financial Analyst,Manufacturing,Australia,2024.0,72.52,76.49,68.93,110112.87,130705.5,18.70,0.01,16.27,85.99,4,High,70.725,18.70,55.297,62.359948
15047,371,Customer Support Rep,NaN,Japan,2021.0,46.07,46.12,5.62,88931.49,84546.07,-4.93,19.44,68.97,26.02,1,Medium,25.845,4.93,21.593,11.987414
15048,14663,Customer Support Rep,Technology,India,2021.0,43.76,48.94,10.29,81611.13,90995.5,11.50,-16.04,15.46,3.36,4,Medium,27.025,11.50,24.041,1.470336
15049,12202,Truck Driver,Manufacturing,USA,2025.0,89.90,107.87,59.36,142175.13,132660.17,-6.69,10.74,71.55,79.01,5,High,74.630,6.69,55.775,71.029990

Muestra aleatoria de 10 filas:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
6670,6670,HR Manager,Energy,Brazil,2021.0,33.89,27.42,89.58,81485.55,71214.41,-12.60,9.18,22.78,8.68,1,Medium,61.735,12.60,44.210,2.941652
12297,12297,Customer Support Rep,Technology,Australia,2025.0,40.03,47.40,44.38,72288.29,66519.97,-7.98,11.46,26.11,32.22,4,Medium,42.205,7.98,31.720,12.897666
6415,6415,Mechanical Engineer,Finance,USA,2021.0,66.81,66.21,85.81,86211.0,85291.61,-1.07,5.40,22.42,85.14,1,High,76.310,1.07,52.788,56.882034
7799,7799,Marketing Specialist,Retail,Brazil,2020.0,48.96,43.69,13.96,NaN,130271.35,6.07,13.73,11.01,28.49,2,Medium,31.460,6.07,25.593,13.948704
3905,3905,HR Manager,Finance,Japan,2021.0,26.05,26.87,8.79,"$80,841.35",89037.38,10.14,-0.50,19.91,68.28,4,Low,17.420,10.14,16.099,17.786940
14529,14529,Teacher,Finance,Canada,2022.0,23.62,26.34,85.61,90266.14,98209.74,8.80,17.01,77.18,41.59,1,Low,54.615,8.80,37.771,9.823558
92,92,HR Manager,Healthcare,Germany,2023.0,NaN,26.42,58.34,78102.17,83212.91,6.54,4.44,23.80,58.62,4,Low,40.525,6.54,28.548,13.312602
11269,11269,HR Manager,Technology,UK,2025.0,69.08,56.54,39.95,131850.76,126186.1,-4.30,30.12,17.84,73.72,3,High,54.515,4.30,40.907,50.925776
2152,2152,Data Analyst,Retail,India,2024.0,67.30,68.23,37.84,"$121,444.62",117577.61,-3.18,5.16,76.26,73.22,4,High,52.570,3.18,39.226,49.277060
9841,9841,Software Engineer,Education,USA,2023.0,58.99,49.24,70.70,134987.3,NaN,-16.73,-1.23,50.10,78.88,5,Medium,64.845,16.73,49.825,46.531312

#### Analisis de vacios y filas duplicadas

In [318]:
print("Conteo de valores nulos por columna:")
display(df.isnull().sum())

print("Número de filas repetidas:", df.duplicated().sum())

Conteo de valores nulos por columna:

job_id                           0
job_role                         0
industry                       751
country                          0
year                             0
automation_risk_percent        752
ai_replacement_score             0
skill_gap_index                  0
salary_before_usd              753
salary_after_usd               754
salary_change_percent            0
skill_demand_growth_percent      0
remote_feasibility_score         0
ai_adoption_level                0
education_requirement_level      0
automation_risk_category         0
skill_transition_pressure        0
wage_volatility_index            0
reskilling_urgency_score         0
ai_disruption_intensity          0
dtype: int64

Número de filas repetidas: 50

#### Identificación de inconsistencias en valores categoricos

In [319]:
object_columns = df.select_dtypes(include=['object']).columns

for col in object_columns:
    print(f"Distribución de categorias para {col}:")
    display(df[col].value_counts(normalize=True, sort=False).sort_index())

Distribución de categorias para job_role:

job_role
Accountant              0.094352
Customer Support Rep    0.100997
Data Analyst            0.101860
Financial Analyst       0.096412
HR Manager              0.100066
Marketing Specialist    0.103522
Mechanical Engineer     0.101661
Software Engineer       0.098007
Teacher                 0.103256
Truck Driver            0.099867
Name: proportion, dtype: float64

Distribución de categorias para industry:

industry
 Education          0.005944
 Energy             0.006434
 Finance            0.006294
 Healthcare         0.006224
 Manufacturing      0.005315
 Retail             0.005735
 Technology         0.006714
 Transportation     0.007833
EDUCATION           0.006294
ENERGY              0.005525
Education           0.102874
Energy              0.106441
FINANCE             0.006924
Finance             0.110287
HEALTHCARE          0.005665
Healthcare          0.106441
MANUFACTURING       0.005944
Manufacturing       0.102525
RETAIL              0.005245
Retail              0.106861
TECHNOLOGY          0.005525
TRANSPORTATION      0.005245
Technology          0.107490
Transportation      0.107840
education           0.006364
energy              0.006434
finance             0.005944
healthcare          0.007133
manufacturing       0.007413
retail              0.006364
technology          0.006434
transportation      0.006294
Name: proportion, dtype: float64

Distribución de categorias para country:

country
Australia    0.109635
Brazil       0.110565
Canada       0.109236
Germany      0.105781
India        0.109568
Japan        0.109435
Singapore    0.116412
UK           0.114086
USA          0.115282
Name: proportion, dtype: float64

Distribución de categorias para salary_before_usd:

salary_before_usd
$100,225.36    0.00007
$100,226.42    0.00007
$100,242.03    0.00007
$100,247.07    0.00007
$100,347.96    0.00007
                ...
99963.01       0.00007
99964.99       0.00007
99966.34       0.00007
99976.17       0.00007
99990.29       0.00007
Name: proportion, Length: 14235, dtype: float64

Distribución de categorias para salary_after_usd:

salary_after_usd
$94,964.93    0.00007
100008.15     0.00007
100046.45     0.00007
100057.69     0.00007
100058.68     0.00007
               ...
99979.45      0.00007
99982.95      0.00007
99987.37      0.00007
99990.31      0.00007
99993.82      0.00007
Name: proportion, Length: 14239, dtype: float64

Distribución de categorias para automation_risk_category:

automation_risk_category
High      0.299601
Low       0.269302
Medium    0.431096
Name: proportion, dtype: float64

#### Limpieza inicial del dataset

*Puntos a atacar:*

- Repetidos:
  - Detectados: 
    - 50 filas repetidas
  - Estrategia:
    - Se dejara una fila única por cada repetido
- Conflictos en columnas categóricas:
  - Detectados:
    - Industry presenta inconsistencias en su uso de mayúsculas y minúsculas
    - Salary_before_usd y salary_after_usd: floats que estan en formato string y presentan uso inconsistente del carácter "$"
  - Estrategia:
    - Industry sera pasado a solo minúscula de manera general
    - Salary_before_usd y salary_after_usd seran convertidos a float
- Vacios:
  - Detectados:
    - salary_after_usd: 754
    - salary_before_usd: 753
    - automation_risk_percent: 752
    - industry: 751
  - Estrategia:
    - Los casos vacios de Industry se completaran con "unknown"
    - Los vacios de automation_risk_percent seran completados analizando el promedio a nivel job_role/industry.
    - Los vacios de salary_before_usd y salary_after_usd seran completados analizando la mediana a nivel job_role/industry.
      - Se usa la mediana ya que los sueldos muy altos o muy bajos harian del promedio un valor poco representativo.

In [320]:

# Limpieza de duplicados
df = df.drop_duplicates()

muestra_df_pre_conversion = df.isnull().sum().copy()

# Saneamiento de strings
df['industry'] = df['industry'].str.lower().str.strip()

for col in ['salary_before_usd', 'salary_after_usd']:
    df[col] = df[col].str.replace(r'[^\d.]+', '', regex=True).astype(str)

df['salary_before_usd'] = pd.to_numeric(df['salary_before_usd'], errors='coerce')
df['salary_after_usd'] = pd.to_numeric(df['salary_after_usd'], errors='coerce')

muestra_df_post_conversion = df.isnull().sum().copy()

if (muestra_df_pre_conversion.equals(muestra_df_post_conversion)):
    print("Se mantiene la cantidad de nulos pre y post conversión.")
else:
    print("La conversión genero nulos.")

Se mantiene la cantidad de nulos pre y post conversión.

In [321]:

df['industry'] = df['industry'].fillna('unknown')

df['automation_risk_percent'] = df['automation_risk_percent'].fillna(
    df.groupby(['job_role', 'industry'])['automation_risk_percent'].transform('mean')
)

df['salary_before_usd'] = df['salary_before_usd'].fillna(
    df.groupby(['job_role', 'industry'])['salary_before_usd'].transform('median')
)

df['salary_after_usd'] = df['salary_after_usd'].fillna(
    df.groupby(['job_role', 'industry'])['salary_after_usd'].transform('median')
)

nulos_restantes = df.isnull().sum().sum()

if nulos_restantes == 0:
    print("Limpieza completa.")
else:
    print(f"Restan {nulos_restantes} valores nulos.")

Limpieza completa.

#### Añadido pre análisis: generación de copia para outliers

Se genera una copia del dataset previo al tratamiento de los outliers. El análisis de los mismos se detalla en la sección correspondiente. 

Los outliers son eliminados de la muestra.

In [322]:
df_outliers = df.copy()

In [323]:
for col in ['salary_before_usd', 'salary_after_usd']:
    
    Q1_grupal = df.groupby(['job_role', 'country'])[col].transform('quantile', q=0.25)
    Q3_grupal = df.groupby(['job_role', 'country'])[col].transform('quantile', q=0.75)
    
    IQR_grupal = Q3_grupal - Q1_grupal
    limite_inferior = Q1_grupal - 1.5 * IQR_grupal
    limite_superior = Q3_grupal + 1.5 * IQR_grupal
    
    df = df[(df[col] >= limite_inferior) & (df[col] <= limite_superior)]

### 4. Fase II: Análisis Estadístico y Exploratorio (EDA)
Utilizando las librerías Pandas y NumPy, resuelvan las siguientes problemáticas:
- **Volatilidad de Ingresos**: Calculen el rango y la varianza de los salarios antes y después de la IA. ¿Qué nos dice esto sobre la estabilidad del sector?
- **Brecha de Habilidades**: Determinen el promedio de `skill_gap_index` por país y encuentren dónde es más crítico el desfase formativo.
- **Detección de Outliers**: Identifiquen salarios que desafíen los rangos normales del mercado (valores negativos o extremos) y decidan su tratamiento.

#### Volatilidad de Ingresos

En este caso se agrupo por job_role y country, considerando el mismo puesto dentro del mercado local. Posteriormente se obtuvo el porcentaje de incremento o decremento entre los valores pre y post tanto de rango como varianza. Dichos valores fueron promediados para tener un indicador general del estado del mercado.

In [324]:
grupos = df.groupby(['job_role', 'country'])

varianzas = grupos[['salary_before_usd', 'salary_after_usd']].var()
maximos = grupos[['salary_before_usd', 'salary_after_usd']].max()
minimos = grupos[['salary_before_usd', 'salary_after_usd']].min()

volatilidad_df = varianzas.rename(columns={'salary_before_usd': 'var_pre_ia','salary_after_usd': 'var_post_ia'})

volatilidad_df['rango_pre_ia'] = maximos['salary_before_usd'] - minimos['salary_before_usd']
volatilidad_df['rango_post_ia'] = maximos['salary_after_usd'] - minimos['salary_after_usd']

columnas_finales = ['rango_pre_ia', 'var_pre_ia', 'rango_post_ia', 'var_post_ia']
volatilidad_df = volatilidad_df[columnas_finales].reset_index()

display(volatilidad_df)

volatilidad_df['var_porcentual_rango'] = ((volatilidad_df['rango_post_ia'] - volatilidad_df['rango_pre_ia']) / volatilidad_df['rango_pre_ia']) * 100
volatilidad_df['var_porcentual_varianza'] = ((volatilidad_df['var_post_ia'] - volatilidad_df['var_pre_ia']) / volatilidad_df['var_pre_ia']) * 100

volatilidad_df = volatilidad_df.replace([np.inf, -np.inf], np.nan)

columnas_variacion = ['job_role', 'country', 'var_porcentual_rango', 'var_porcentual_varianza']

tabla_variacion = volatilidad_df[columnas_variacion]

print("Tabla de Variación Porcentual")
display(tabla_variacion)

promedio_var_rango = tabla_variacion['var_porcentual_rango'].mean()
promedio_var_varianza = tabla_variacion['var_porcentual_varianza'].mean()

print("\nPromedios Generales de Impacto de la IA")
print(f"Variación promedio del Rango: {promedio_var_rango:.2f}%")
print(f"Variación promedio de la Varianza: {promedio_var_varianza:.2f}%")

,job_role,country,rango_pre_ia,var_pre_ia,rango_post_ia,var_post_ia
0,Accountant,Australia,119205.05,1.122373e+09,145474.02,1.440278e+09
1,Accountant,Brazil,118391.03,1.034458e+09,129502.96,1.011433e+09
2,Accountant,Canada,119847.86,1.215958e+09,142582.90,1.178905e+09
3,Accountant,Germany,119025.59,1.187382e+09,140658.15,1.195715e+09
4,Accountant,India,119198.28,1.182384e+09,133319.62,1.279434e+09
...,...,...,...,...,...,...
85,Truck Driver,India,115767.69,1.030928e+09,131472.60,1.176907e+09
86,Truck Driver,Japan,118955.57,1.101016e+09,151143.03,1.173622e+09
87,Truck Driver,Singapore,119243.42,1.153831e+09,157056.01,1.362655e+09
88,Truck Driver,UK,118993.50,1.156397e+09,142658.84,1.269096e+09
89,Truck Driver,USA,117991.67,1.071431e+09,141402.15,1.171480e+09

Tabla de Variación Porcentual

        job_role    country  var_porcentual_rango  var_porcentual_varianza
0     Accountant  Australia             22.036793                28.324321
1     Accountant     Brazil              9.385787                -2.225797
2     Accountant     Canada             18.969917                -3.047231
3     Accountant    Germany             18.174714                 0.701851
4     Accountant      India             11.846933                 8.208053
..           ...        ...                   ...                      ...
85  Truck Driver      India             13.565884                14.159870
86  Truck Driver      Japan             27.058388                 6.594522
87  Truck Driver  Singapore             31.710421                18.098307
88  Truck Driver         UK             19.887927                 9.745670
89  Truck Driver        USA             19.840790                 9.337898

[90 rows x 4 columns]

Promedios Generales de Impacto de la IA
Variación promedio del Rango: 20.61%
Variación promedio de la Varianza: 8.57%

Sintetizado, comparando los valores pre y post IA se ve un aumento general del Rango en los sueldos y una mayor varianza. En otras palabras, la distancia entre el sueldo menor y el mayor aumento y la muestra exhibe sueldos muy dispares entre si. Dos personas pueden estar cobrando montos totalmente diferentes para el mismo puesto.

#### Brecha de Habilidades

In [325]:
brecha_por_pais = df.groupby('country')['skill_gap_index'].mean().sort_values(ascending=False)

print("Promedio de Skill Gap Index por País")
display(brecha_por_pais)

pais_critico = brecha_por_pais.idxmax()
valor_critico = brecha_por_pais.max()

print(f"\nEl desfase formativo más crítico se encuentra en: {pais_critico} (Índice promedio: {valor_critico:.2f})")

Promedio de Skill Gap Index por País

country
India        50.783774
Germany      50.668442
USA          50.487548
Canada       49.897576
Brazil       49.894550
Japan        49.874927
UK           49.590612
Australia    49.566348
Singapore    49.392746
Name: skill_gap_index, dtype: float64

El desfase formativo más crítico se encuentra en: India (Índice promedio: 50.78)

#### Detección de outliers

Para detectar los outliers se usa IQR. Se segmenta por job_role y country para que el rango comprenda puestos similares dentro la misma economia local.

En resumen, el IQR representa el eje central de los datos obtenido a partir de restar el cuartil 25 al cuartil 75. No representa el punto medio sino la distancia entre el Q25 y Q75.

Posteriormente podemos usar dicha distancia multiplicada por 1,5 para establecer topes inferiores y superiores (conocidos como barreras de Tukey) para determinar los outliers.

Aquellos outliers detectados fueron eliminados en un paso previo. En el bloque siguiente se aprecia la detección en detalle de los mismos usando una copia de respaldo previo a dicho tratamiento.

Referencia: https://metricgate.com/docs/es/interquartile-range-outlier/

In [326]:
for col in ['salary_before_usd', 'salary_after_usd']:

    print(f"\nAnálisis de outliers agrupados para {col}")

    Q1_grupal = df_outliers.groupby(['job_role', 'country'])[col].transform('quantile', q=0.25)
    Q3_grupal = df_outliers.groupby(['job_role', 'country'])[col].transform('quantile', q=0.75)
    
    IQR_grupal = Q3_grupal - Q1_grupal
    limite_inferior_grupal = Q1_grupal - 1.5 * IQR_grupal
    limite_superior_grupal = Q3_grupal + 1.5 * IQR_grupal

    df_outliers['IQR_grupal'] = IQR_grupal
    df_outliers['Q1_grupal'] = Q1_grupal
    df_outliers['Q3_grupal'] = Q3_grupal
    df_outliers['limite_inf_aplicado'] = limite_inferior_grupal
    df_outliers['limite_sup_aplicado'] = limite_superior_grupal

    outliers_inf = df_outliers[df_outliers[col] < df_outliers['limite_inf_aplicado']]
    outliers_sup = df_outliers[df_outliers[col] > df_outliers['limite_sup_aplicado']]

    cols_a_mostrar = ['job_id', 'job_role', 'industry', 'country', col, 'limite_inf_aplicado', 'Q1_grupal', 'IQR_grupal', 'Q3_grupal', 'limite_sup_aplicado']

    print(f"Sueldos atípicamente bajos: {len(outliers_inf)}")
    if len(outliers_inf) > 0:
        display(outliers_inf[cols_a_mostrar])

    print(f"Sueldos atípicamente altos: {len(outliers_sup)}")
    if len(outliers_sup) > 0:
        display(outliers_sup[cols_a_mostrar])

    df_outliers = df_outliers.drop(columns=['limite_inf_aplicado', 'limite_sup_aplicado', 'IQR_grupal', 'Q1_grupal', 'Q3_grupal'])

Análisis de outliers agrupados para salary_before_usd
Sueldos atípicamente bajos: 0
Sueldos atípicamente altos: 0

Análisis de outliers agrupados para salary_after_usd
Sueldos atípicamente bajos: 0
Sueldos atípicamente altos: 11

,job_id,job_role,industry,country,salary_after_usd,limite_inf_aplicado,Q1_grupal,IQR_grupal,Q3_grupal,limite_sup_aplicado
362,362,Data Analyst,transportation,Australia,269712.10,-37028.00250,56602.5900,62420.3950,119022.985,212653.57750
3872,3872,Customer Support Rep,technology,Canada,672289.50,-21790.37000,64510.7200,57534.0600,122044.780,208345.87000
5607,5607,Truck Driver,finance,USA,915099.00,-18230.08000,65538.6800,55845.8400,121384.520,205153.28000
6485,6485,Mechanical Engineer,finance,USA,338873.10,-34054.65625,56027.3975,60054.7025,116082.100,206164.15375
7238,7238,Customer Support Rep,healthcare,Japan,183798.52,9973.02000,71889.3300,41277.5400,113166.870,175083.18000
9448,9448,Accountant,retail,Brazil,942310.20,-11314.17500,58912.2100,46817.5900,105729.800,175956.18500
11904,11904,Accountant,manufacturing,Japan,569331.80,-30169.16000,61045.0600,60809.4800,121854.540,213068.76000
14205,14205,Financial Analyst,healthcare,Germany,371779.70,-18764.79000,59689.8300,52303.0800,111992.910,190447.53000
14605,14605,Customer Support Rep,manufacturing,Canada,318754.90,-21790.37000,64510.7200,57534.0600,122044.780,208345.87000
14719,14719,Teacher,transportation,Brazil,1094112.30,-16950.44000,57401.3050,49567.8300,106969.135,181320.88000
14992,14992,HR Manager,energy,Australia,634220.10,-13127.62500,61638.7350,49844.2400,111482.975,186249.33500

### 5. Fase III: Visualización y Comunicación
Diseñen las siguientes piezas utilizando Matplotlib:
- **Gráfico de Evolución**: Tendencia anual del salario promedio en finanzas desde 2020 a 2026.
- **Gráfico de Distribución (Pie/Pie Chart)**: Distribución de los roles según su categoría de riesgo de automatización.
- **Heatmap o Barras Geográficas**: Comparativa del `ai_adoption_level` por país para este sector.

### 6. Fase IV: Reflexión Crítica (Anti-LLM)
*Responda basándose estrictamente en los hallazgos de su procesamiento de datos:*
- ¿Existe evidencia de que la IA esté "empobreciendo" los roles tradicionales de finanzas?
- Según sus datos, ¿la factibilidad de trabajo remoto protege o expone más al trabajador financiero frente al reemplazo por IA?

### 7. Requerimientos de Entrega y Defensa
1.  **Informe Profesional**: PDF o Markdown con resumen ejecutivo, bitácora de saneamiento e interpretación de resultados.
2.  **Código Fuente**: Script o Notebook estructurado, comentado y reproducible.
3.  **Defensa Oral**: Justificación técnica de la limpieza e interpretación de las visualizaciones ante el curso.