# Trabajo Práctico: Impacto de la IA en el Empleo (2020-2026)
## Sector Asignado: Finanzas (Finance)

### 1. Introducción Académica
El avance de la Inteligencia Artificial no es solo un fenómeno técnico, sino una fuerza socioeconómica que está redefiniendo la naturaleza del trabajo. En los próximos años, diversos sectores experimentarán cambios sin precedentes en sus estructuras salariales, demandas de habilidades y estabilidad laboral. Este Trabajo Práctico propone analizar estas tendencias con rigor científico y pensamiento crítico.

### 2. Ficha del Proyecto: Grupo 2
*   **Sector**: Finanzas.
*   **Objetivo General**: Analizar el impacto de la IA en la volatilidad salarial y la brecha de habilidades dentro del sector financiero, identificando países con mayor estrés de transición.

#### Setup y parametros

In [232]:
import pandas as pd
import numpy as np
# Display para mostrar los DF de manera más prolija
from IPython.display import display

csv_base_file_path = '../MaterialBase/ai_job_replacement_dirty.csv'

### 3. Fase I: Diagnóstico y Saneamiento (Caja Negra)
Ustedes trabajarán con la fuente de datos `ai_job_replacement_dirty.csv`. **Advertencia**: La fuente posee anomalías estructuradas.
- **Auditoría de Calidad**: Realicen un reporte inicial sobre el estado de la información. Deben identificar inconsistencias lógicas, errores de formato y vacíos de datos sin guía externa.
- **Protocolo de Curación**: Implementen y documenten un proceso sistemático de limpieza. Cada decisión (casteo de tipos, manejo de nulos, eliminación de duplicados) debe estar técnicamente justificada en su bitácora.
- **Normalización**: Traduzcan y estandaricen los campos para asegurar una lectura fluida en español.

#### Carga y muestra rápida

In [233]:
df = pd.read_csv(csv_base_file_path)

print("Info del DataFrame:")
display(df.info())

print("Primeras filas del DataFrame:")
display(df.head())
print("Últimas filas del DataFrame:")
display(df.tail())
print("Muestra aleatoria de 10 filas:")
display(df.sample(n=10))

Info del DataFrame:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15050 entries, 0 to 15049
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   job_id                       15050 non-null  int64
 1   job_role                     15050 non-null  object
 2   industry                     14299 non-null  object
 3   country                      15050 non-null  object
 4   year                         15050 non-null  float64
 5   automation_risk_percent      14298 non-null  float64
 6   ai_replacement_score         15050 non-null  float64
 7   skill_gap_index              15050 non-null  float64
 8   salary_before_usd            14297 non-null  object
 9   salary_after_usd             14296 non-null  object
 10  salary_change_percent        15050 non-null  float64
 11  skill_demand_growth_percent  15050 non-null  float64
 12  remote_feasibility_score     15050 non-null  float64
 13  ai_adoption_level            15050 non-null  float64
 14  education_requirement_level  15050 non-null  int64
 15  automation_risk_category     15050 non-null  object
 16  skill_transition_pressure    15050 non-null  float64
 17  wage_volatility_index        15050 non-null  float64
 18  reskilling_urgency_score     15050 non-null  float64
 19  ai_disruption_intensity      15050 non-null  float64
dtypes: float64(12), int64(2), object(6)
memory usage: 2.3+ MB

None

Primeras filas del DataFrame:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
0,0,Data Analyst,Technology,Canada,2021.0,26.22,30.94,73.20,101839.02,99454.42,-2.34,2.66,15.23,86.62,2,Low,49.710,2.34,33.150,22.711764
1,1,Accountant,FINANCE,Brazil,2020.0,52.08,56.41,2.06,146389.18,139516.59,-4.69,10.43,26.36,18.34,5,Medium,27.070,4.69,22.857,9.551472
2,2,Teacher,Technology,USA,2020.0,31.30,31.61,43.19,64947.5,58369.41,-10.13,8.14,36.29,36.64,2,Medium,37.245,10.13,28.516,11.468320
3,3,Customer Support Rep,Technology,Brazil,2021.0,56.92,63.42,19.97,NaN,86715.7,-5.44,6.11,64.68,17.05,5,Medium,38.445,5.44,30.391,9.704860
4,4,Teacher,manufacturing,Japan,2024.0,14.55,17.17,96.56,127007.68,NaN,-6.01,2.08,71.58,44.02,3,Low,55.555,6.01,36.591,6.404910

Últimas filas del DataFrame:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
15045,13610,Marketing Specialist,Transportation,Australia,2022.0,22.03,20.22,39.80,78791.26,NaN,-0.24,19.22,15.01,60.05,3,Low,30.915,0.24,20.824,13.229015
15046,1670,Financial Analyst,Manufacturing,Australia,2024.0,72.52,76.49,68.93,110112.87,130705.5,18.70,0.01,16.27,85.99,4,High,70.725,18.70,55.297,62.359948
15047,371,Customer Support Rep,NaN,Japan,2021.0,46.07,46.12,5.62,88931.49,84546.07,-4.93,19.44,68.97,26.02,1,Medium,25.845,4.93,21.593,11.987414
15048,14663,Customer Support Rep,Technology,India,2021.0,43.76,48.94,10.29,81611.13,90995.5,11.50,-16.04,15.46,3.36,4,Medium,27.025,11.50,24.041,1.470336
15049,12202,Truck Driver,Manufacturing,USA,2025.0,89.90,107.87,59.36,142175.13,132660.17,-6.69,10.74,71.55,79.01,5,High,74.630,6.69,55.775,71.029990

Muestra aleatoria de 10 filas:

,job_id,job_role,industry,country,year,automation_risk_percent,ai_replacement_score,skill_gap_index,salary_before_usd,salary_after_usd,salary_change_percent,skill_demand_growth_percent,remote_feasibility_score,ai_adoption_level,education_requirement_level,automation_risk_category,skill_transition_pressure,wage_volatility_index,reskilling_urgency_score,ai_disruption_intensity
5175,5175,Software Engineer,Retail,Japan,2023.0,43.47,35.58,88.46,38133.88,36378.82,-4.60,24.18,19.25,85.62,1,Medium,65.965,4.60,45.306,37.219014
6511,6511,Financial Analyst,HEALTHCARE,India,2022.0,20.78,20.74,57.00,43642.62,44617.11,2.23,4.84,30.64,64.72,5,Low,38.890,2.23,26.081,13.448816
7847,7847,HR Manager,Retail,Singapore,2024.0,18.45,15.36,19.34,87939.55,84611.95,-3.78,-10.13,12.64,62.76,5,Low,18.895,3.78,14.316,11.579220
13176,13176,Data Analyst,Education,UK,2020.0,10.36,10.71,81.38,112958.83,128071.05,13.38,1.75,53.13,64.39,2,Low,45.870,13.38,32.572,6.670804
12545,12545,Truck Driver,Healthcare,Canada,2020.0,59.26,49.73,83.74,54746.69,55767.78,1.87,2.17,12.51,61.78,5,Medium,71.500,1.87,49.387,36.610828
11906,11906,Accountant,Energy,Canada,2025.0,20.57,24.32,17.15,52331.15,45879.43,-12.33,-0.63,38.16,3.99,2,Low,18.860,12.33,17.072,0.820743
6061,6061,Customer Support Rep,Retail,USA,2025.0,88.24,74.96,67.01,125454.53,148877.86,18.67,-15.95,30.46,92.36,2,High,77.625,18.67,61.000,81.498464
3838,3838,Customer Support Rep,healthcare,Germany,2021.0,87.55,97.66,69.20,108609.54,112261.87,3.36,10.17,93.46,55.31,3,High,78.375,3.36,56.788,48.423905
3398,3398,HR Manager,MANUFACTURING,USA,2020.0,61.52,56.02,87.26,112590.02,102650.93,-8.83,-13.78,75.40,21.16,2,High,74.390,8.83,53.435,13.017632
8551,8551,Truck Driver,Manufacturing,USA,2021.0,87.65,71.47,98.96,122649.26,105829.64,-13.71,-8.19,53.47,87.55,2,High,93.305,13.71,68.861,76.737575

#### Analisis de vacios y filas duplicadas

In [234]:
print("Conteo de valores nulos por columna:")
display(df.isnull().sum())

print("Número de filas repetidas:", df.duplicated().sum())

Conteo de valores nulos por columna:

job_id                           0
job_role                         0
industry                       751
country                          0
year                             0
automation_risk_percent        752
ai_replacement_score             0
skill_gap_index                  0
salary_before_usd              753
salary_after_usd               754
salary_change_percent            0
skill_demand_growth_percent      0
remote_feasibility_score         0
ai_adoption_level                0
education_requirement_level      0
automation_risk_category         0
skill_transition_pressure        0
wage_volatility_index            0
reskilling_urgency_score         0
ai_disruption_intensity          0
dtype: int64

Número de filas repetidas: 50

#### Identificación de inconsistencias en valores categoricos

In [235]:
object_columns = df.select_dtypes(include=['object']).columns

for col in object_columns:
    print(f"Distribución de categorias para {col}:")
    display(df[col].value_counts(normalize=True, sort=False).sort_index())

Distribución de categorias para job_role:

job_role
Accountant              0.094352
Customer Support Rep    0.100997
Data Analyst            0.101860
Financial Analyst       0.096412
HR Manager              0.100066
Marketing Specialist    0.103522
Mechanical Engineer     0.101661
Software Engineer       0.098007
Teacher                 0.103256
Truck Driver            0.099867
Name: proportion, dtype: float64

Distribución de categorias para industry:

industry
 Education          0.005944
 Energy             0.006434
 Finance            0.006294
 Healthcare         0.006224
 Manufacturing      0.005315
 Retail             0.005735
 Technology         0.006714
 Transportation     0.007833
EDUCATION           0.006294
ENERGY              0.005525
Education           0.102874
Energy              0.106441
FINANCE             0.006924
Finance             0.110287
HEALTHCARE          0.005665
Healthcare          0.106441
MANUFACTURING       0.005944
Manufacturing       0.102525
RETAIL              0.005245
Retail              0.106861
TECHNOLOGY          0.005525
TRANSPORTATION      0.005245
Technology          0.107490
Transportation      0.107840
education           0.006364
energy              0.006434
finance             0.005944
healthcare          0.007133
manufacturing       0.007413
retail              0.006364
technology          0.006434
transportation      0.006294
Name: proportion, dtype: float64

Distribución de categorias para country:

country
Australia    0.109635
Brazil       0.110565
Canada       0.109236
Germany      0.105781
India        0.109568
Japan        0.109435
Singapore    0.116412
UK           0.114086
USA          0.115282
Name: proportion, dtype: float64

Distribución de categorias para salary_before_usd:

salary_before_usd
$100,225.36    0.00007
$100,226.42    0.00007
$100,242.03    0.00007
$100,247.07    0.00007
$100,347.96    0.00007
                ...
99963.01       0.00007
99964.99       0.00007
99966.34       0.00007
99976.17       0.00007
99990.29       0.00007
Name: proportion, Length: 14235, dtype: float64

Distribución de categorias para salary_after_usd:

salary_after_usd
$94,964.93    0.00007
100008.15     0.00007
100046.45     0.00007
100057.69     0.00007
100058.68     0.00007
               ...
99979.45      0.00007
99982.95      0.00007
99987.37      0.00007
99990.31      0.00007
99993.82      0.00007
Name: proportion, Length: 14239, dtype: float64

Distribución de categorias para automation_risk_category:

automation_risk_category
High      0.299601
Low       0.269302
Medium    0.431096
Name: proportion, dtype: float64

#### Limpieza inicial del dataset

*Puntos a atacar:*

- Repetidos:
  - Detectados: 
    - 50 filas repetidas
  - Estrategia:
    - Se dejara una fila única por cada repetido
- Conflictos en columnas categóricas:
  - Detectados:
    - Industry presenta inconsistencias en su uso de mayúsculas y minúsculas
    - Salary_before_usd y salary_after_usd: floats que estan en formato string y presentan uso inconsistente del carácter "$"
  - Estrategia:
    - Industry sera pasado a solo minúscula de manera general
    - Salary_before_usd y salary_after_usd seran convertidos a float
- Vacios:
  - Detectados:
    - salary_after_usd: 754
    - salary_before_usd: 753
    - automation_risk_percent: 752
    - industry: 751
  - Estrategia:
    - Los casos vacios de Industry se completaran con "unknown"
    - Los vacios de automation_risk_percent seran completados analizando el promedio a nivel job_role/industry.
    - Los vacios de salary_before_usd y salary_after_usd seran completados analizando la mediana a nivel job_role/industry.
      - Se usa la mediana ya que los sueldos muy altos o muy bajos harian del promedio un valor poco representativo.

In [236]:

# Limpieza de duplicados
df = df.drop_duplicates()

muestra_df_pre_conversion = df.isnull().sum().copy()

# Saneamiento de strings
df['industry'] = df['industry'].str.lower().str.strip()

for col in ['salary_before_usd', 'salary_after_usd']:
    df[col] = df[col].str.replace(r'[^\d.]+', '', regex=True).astype(str)

df['salary_before_usd'] = pd.to_numeric(df['salary_before_usd'], errors='coerce')
df['salary_after_usd'] = pd.to_numeric(df['salary_after_usd'], errors='coerce')

muestra_df_post_conversion = df.isnull().sum().copy()

if (muestra_df_pre_conversion.equals(muestra_df_post_conversion)):
    print("Se mantiene la cantidad de nulos pre y post conversión.")
else:
    print("La conversión genero nulos.")

Se mantiene la cantidad de nulos pre y post conversión.

In [237]:

df['industry'] = df['industry'].fillna('unknown')

df['automation_risk_percent'] = df['automation_risk_percent'].fillna(
    df.groupby(['job_role', 'industry'])['automation_risk_percent'].transform('mean')
)

df['salary_before_usd'] = df['salary_before_usd'].fillna(
    df.groupby(['job_role', 'industry'])['salary_before_usd'].transform('median')
)

df['salary_after_usd'] = df['salary_after_usd'].fillna(
    df.groupby(['job_role', 'industry'])['salary_after_usd'].transform('median')
)

nulos_restantes = df.isnull().sum().sum()

if nulos_restantes == 0:
    print("Limpieza completa.")
else:
    print(f"Restan {nulos_restantes} valores nulos.")

Limpieza completa.

#### Añadido pre análisis: generación de copia para outliers

In [238]:
df_outliers = df.copy()

### 4. Fase II: Análisis Estadístico y Exploratorio (EDA)
Utilizando las librerías Pandas y NumPy, resuelvan las siguientes problemáticas:
- **Volatilidad de Ingresos**: Calculen el rango y la varianza de los salarios antes y después de la IA. ¿Qué nos dice esto sobre la estabilidad del sector?
- **Brecha de Habilidades**: Determinen el promedio de `skill_gap_index` por país y encuentren dónde es más crítico el desfase formativo.
- **Detección de Outliers**: Identifiquen salarios que desafíen los rangos normales del mercado (valores negativos o extremos) y decidan su tratamiento.

#### Volatilidad de Ingresos

In [239]:
var_antes = df['salary_before_usd'].var()
var_despues = df['salary_after_usd'].var()

rango_antes = df['salary_before_usd'].max() - df['salary_before_usd'].min()
rango_despues = df['salary_after_usd'].max() - df['salary_after_usd'].min()

print("Valores Pre IA")
print(f"Rango: {rango_antes}")
print(f"Varianza: {var_antes:.2f}")

print("\nValores Post IA")
print(f"Rango: {rango_despues}")
print(f"Varianza: {var_despues:.2f}")

Valores Pre IA
Rango: 119980.37
Varianza: 1130733378.82

Valores Post IA
Rango: 1072136.05
Varianza: 1459413277.99

#### Brecha de Habilidades

In [240]:
brecha_por_pais = df.groupby('country')['skill_gap_index'].mean().sort_values(ascending=False)

print("Promedio de Skill Gap Index por País")
display(brecha_por_pais)

pais_critico = brecha_por_pais.idxmax()
valor_critico = brecha_por_pais.max()

print(f"\nEl desfase formativo más crítico se encuentra en: {pais_critico} (Índice promedio: {valor_critico:.2f})")

Promedio de Skill Gap Index por País

country
India        50.783774
Germany      50.641942
USA          50.443489
Brazil       49.893713
Japan        49.888999
Canada       49.874640
UK           49.590612
Australia    49.581096
Singapore    49.392746
Name: skill_gap_index, dtype: float64

El desfase formativo más crítico se encuentra en: India (Índice promedio: 50.78)

#### Detección de outliers

Para detectar los outliers se usa IQR.

En resumen, el IQR representa el eje central de los datos obtenido a partir de restar el cuartil 25 al cuartil 75. No representa el punto medio sino la distancia entre el Q25 y Q75.

Posteriormente podemos usar dicha distancia multiplicada por 1,5 para establecer topes inferiores y superiores (conocidos como barreras de Tukey) para determinar los outliers.

Referencia: https://metricgate.com/docs/es/interquartile-range-outlier/

In [ ]:
for col in ['salary_before_usd', 'salary_after_usd']:

    print(f"\nAnálisis de outliers agrupados para {col}")

    Q1_grupal = df_outliers.groupby(['job_role', 'industry'])[col].transform('quantile', q=0.25)
    Q3_grupal = df_outliers.groupby(['job_role', 'industry'])[col].transform('quantile', q=0.75)
    
    IQR_grupal = Q3_grupal - Q1_grupal
    limite_inferior_grupal = Q1_grupal - 1.5 * IQR_grupal
    limite_superior_grupal = Q3_grupal + 1.5 * IQR_grupal

    df_outliers['IQR_grupal'] = IQR_grupal
    df_outliers['Q1_grupal'] = Q1_grupal
    df_outliers['Q3_grupal'] = Q3_grupal
    df_outliers['limite_inf_aplicado'] = limite_inferior_grupal
    df_outliers['limite_sup_aplicado'] = limite_superior_grupal

    outliers_inf = df_outliers[df_outliers[col] < df_outliers['limite_inf_aplicado']]
    outliers_sup = df_outliers[df_outliers[col] > df_outliers['limite_sup_aplicado']]

    cols_a_mostrar = ['job_id', 'job_role', 'industry', 'country', col, 'limite_inf_aplicado', 'Q1_grupal', 'IQR_grupal', 'Q3_grupal', 'limite_sup_aplicado']

    print(f"Sueldos atípicamente bajos: {len(outliers_inf)}")
    if len(outliers_inf) > 0:
        display(outliers_inf[cols_a_mostrar])

    print(f"Sueldos atípicamente altos: {len(outliers_sup)}")
    if len(outliers_sup) > 0:
        display(outliers_sup[cols_a_mostrar])

df_outliers = df_outliers.drop(columns=['limite_inf_aplicado', 'limite_sup_aplicado', 'IQR_grupal', 'Q1_grupal', 'Q3_grupal'])

Análisis de outliers agrupados para salary_before_usd
Sueldos atípicamente bajos: 0

Sueldos atípicamente altos: 0

Análisis de outliers agrupados para salary_after_usd

Sueldos atípicamente bajos: 0

Sueldos atípicamente altos: 12

,job_id,job_role,industry,country,salary_after_usd,limite_inf_aplicado,Q1_grupal,IQR_grupal,Q3_grupal,limite_sup_aplicado
362,362,Data Analyst,transportation,Australia,269712.10,-22233.48750,56437.5450,52447.3550,108884.9000,187555.93250
550,550,Teacher,education,Japan,179562.77,-6078.21000,63294.4500,46248.4400,109542.8900,178915.55000
3872,3872,Customer Support Rep,technology,Canada,672289.50,-26853.50500,62200.3175,59369.2150,121569.5325,210623.35500
5607,5607,Truck Driver,finance,USA,915099.00,-26232.37000,58755.7100,56658.7200,115414.4300,200402.51000
6485,6485,Mechanical Engineer,finance,USA,338873.10,-19073.74000,60392.4800,52977.4800,113369.9600,192836.18000
8587,8587,Teacher,education,Australia,186753.36,-6078.21000,63294.4500,46248.4400,109542.8900,178915.55000
9448,9448,Accountant,retail,Brazil,942310.20,-23037.64250,66699.0925,59824.4900,126523.5825,216260.31750
11904,11904,Accountant,manufacturing,Japan,569331.80,-35121.44000,57130.5700,61501.3400,118631.9100,210883.92000
14205,14205,Financial Analyst,healthcare,Germany,371779.70,-23281.05500,62033.6800,56876.4900,118910.1700,204224.90500
14605,14605,Customer Support Rep,manufacturing,Canada,318754.90,-16972.30250,65308.3600,54853.7750,120162.1350,202442.79750
14719,14719,Teacher,transportation,Brazil,1094112.30,-2352.42000,69591.3600,47962.5200,117553.8800,189497.66000
14992,14992,HR Manager,energy,Australia,634220.10,-19674.68625,62940.1500,55076.5575,118016.7075,200631.54375

### 5. Fase III: Visualización y Comunicación
Diseñen las siguientes piezas utilizando Matplotlib:
- **Gráfico de Evolución**: Tendencia anual del salario promedio en finanzas desde 2020 a 2026.
- **Gráfico de Distribución (Pie/Pie Chart)**: Distribución de los roles según su categoría de riesgo de automatización.
- **Heatmap o Barras Geográficas**: Comparativa del `ai_adoption_level` por país para este sector.

### 6. Fase IV: Reflexión Crítica (Anti-LLM)
*Responda basándose estrictamente en los hallazgos de su procesamiento de datos:*
- ¿Existe evidencia de que la IA esté "empobreciendo" los roles tradicionales de finanzas?
- Según sus datos, ¿la factibilidad de trabajo remoto protege o expone más al trabajador financiero frente al reemplazo por IA?

### 7. Requerimientos de Entrega y Defensa
1.  **Informe Profesional**: PDF o Markdown con resumen ejecutivo, bitácora de saneamiento e interpretación de resultados.
2.  **Código Fuente**: Script o Notebook estructurado, comentado y reproducible.
3.  **Defensa Oral**: Justificación técnica de la limpieza e interpretación de las visualizaciones ante el curso.